language: ruby
rvm:
- 2.3.3

install: gem install jekyll html-proofer
script: bundle exec jekyll build && htmlproofer ./_site

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 21d91c4f2fc56872668d0346a78c46d7960c0eee # Set in travis-ci.org dashboard
  on:
    branch: master

sudo: false
