# Site
title:              David Wu's Homepage
bio:                'I am currently a high school student at Internatsschule Schloss Hansenberg, Germany. In my freetime, I do programming and sport.'
description:        "This is my Github page."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/D_logo.png'
background:         'assets/img/background.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://pl4gue.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
google:
  plus:             'u/0/100443709803923106442'
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              david10608@gmail.com
twitter:            pl4gue_dwu
#facebook:           -
github-url:         Pl4gue
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
medium:            '@david10608'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
