# main text of home
title: David Wu
name: David Wu
bio: German High School Student, Programming Enthusiast, Freelancer, GNU/Linux Lover, Sports Fanatic

# twitter summary info
description: David Wu

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg
profile_picture: assets/images/pb.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: false
resume-url: docs/cv

url: http://david-wu.me/

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: 'UA-109087116-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: pl4gue # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
#facebook: myfacebook
twitter: pl4gue_dwu
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# linkedin: mylinkedin
# youtube: myyoutube
#spotify: david10608
snapchat: daviidwu
ubuntuone: pl4gue
github: pl4gue
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
#medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: david10608@gmail.com

authors:
    pl4gue:
        name: David Wu
        bio: A german high school student who likes doing things with code, playing around with GNU/Linux and being active.
        external-image: false
        picture: assets/images/logo_square.png
        twitter: pl4gue_dwu

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

projects: true
about: true
hire: true
achievements: true
#blog: true

read-time: true
show-tags: true

related: true
# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

exclude: [vendor]

show-author: true
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-admin
  - jekyll-redirect-from

jekyll-mentions:
    base_url: https://github.com
